#!/usr/bin/env python

# Copyright 2017 Red Hat Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import urllib2
import getpass
import json
import argparse
from base64 import b64encode

parser = argparse.ArgumentParser(description='Convert GitHub issue into JIRA issue')

parser.add_argument('issuenum', metavar='ISSUE', nargs='+', type=int,
        help='The issue number')
parser.add_argument('--repo', metavar='REPO', type=str,
        default='EnMasseProject/enmasse', help='The name of the repository (default: EnMasseProject/enmasse)')
parser.add_argument('--user', metavar='USER', type=str,
        help='The name of the user in the JIRA system')
parser.add_argument('--project', metavar='PROJECT', type=str,
        default='ENTMQMAAS', help='The project in the JIRA system (default: ENTMQMAAS)')
parser.add_argument('--githubbaseurl', metavar='GITHUBURL', type=str,
        default='https://api.github.com', 
        help='The base URL for github (default: https://api.github.com)')
parser.add_argument('--jirabaseurl', metavar='JIRAURL', type=str,
        default='https://issues.jboss.org/rest/api/2', 
        help='The base URL for jira (default: https://issues.jboss.org/rest/api/2)')

parser.add_argument('--usermapping', metavar='USERMAPPING', type=str,
        default='{ "rgodfrey" : "robgodfrey", "grs" : "gordonsim" , "lulf" : "ulf.lilleengen", "tkratky" : "tkratky", "ppatierno" : "ppatiern", "kornys": "dkornel", "k-wall" : "kwall", "RH-sdavey" : "sdavey", "robshelly" : "rshelly", "junezhang" : "zhangjune99", "yih-wang" : "yihwang"  }',
        help='json map of github id to JIRA id')
parser.add_argument('--jiraadmins', metavar='JIRAADMINS', type=str,
        default='[ "robgodfrey", "gordonsim" , "ulf.lilleengen" ]', 
        help='json list of JIRA users who can create issues on behalf of another')
args = parser.parse_args()
username = args.user

if username is None:
    username = raw_input('Username: ')

pw = getpass.getpass()

upwstr = username + ':' + pw
upwstrenc = b64encode(upwstr.encode('utf-8')).strip().decode('utf-8')
usermap = json.loads(args.usermapping)
admins = json.loads(args.jiraadmins)

for issue in args.issuenum:
  url = '%s/repos/%s/issues/%d' % (args.githubbaseurl, args.repo, issue)
  req = urllib2.Request(url)
  res = urllib2.urlopen(req).read()
  githubIssue = json.loads(res)
  
  fields = { 'project' : { 'key': args.project },
             'issuetype' : { 'name': 'Task' },
             'summary' : '[#%d] : %s' % ( githubIssue['number'], githubIssue['title'] ),
             'description' : 'Created from upstream issue [#%d|%s].' % (githubIssue['number'], githubIssue['html_url'] ) }
  mappeduser = usermap[ githubIssue[ 'user' ][ 'login' ] ]
  if username in admins and mappeduser :
    fields[ 'reporter' ] = { 'name' : mappeduser }
  jira = { 'fields': fields }
  
  posturl = '%s/issue/' % ( args.jirabaseurl )
  postreq = urllib2.Request(posturl)
  postreq.add_header('Content-Type','application/json')
  postreq.add_header('Authorization', 'Basic ' + upwstrenc)
  
  postreq.add_data(json.dumps(jira))
 
  postres = urllib2.urlopen(postreq).read()
  jiraResult  = json.loads(postres)
  
  print 'Created issue: %s' % ( jiraResult['key'] )

